name: Scala formatter
on:
  push:
    branches: [ fix/ADP-0000 ]
    paths:
      - '**.scala'
  pull_request:
    branches: [ main ]
    paths:
      - '**.scala'

jobs:
  scalafmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Check for scalafmt conformance
      run: |
        VERSION=3.5.8
        INSTALL_LOCATION=/usr/local/bin/scalafmt-native
        curl -fL https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz | gzip -d > cs
        sudo chmod +x cs
        ./cs setup
        cs install scalafmt
        cs launch scalafmt -- --help
